language: php

services:

cache:
  directories:
    - $HOME/.composer/cache

before_install:

install:
  - composer remove --no-update --no-scripts --dev andreaskasper/cryptocom
  - composer install
  
script: ./vendor/bin/phpunit --configuration ./travis.phpunit.xml.dist
  
stages:
  - coding-standard
  - test

jobs:
  include:
    - stage: coding-standard
      before_install:
      before_script:
      after_script:
      php: 8.0
      env: CS_CHECK=1
    - stage: test
#      php: 5.5
#    - php: 5.6
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
#    - php: 8.0
      dist: trusty
